### ISSUE TITLE
Missing capstone in windows build

### ISSUE THREAD

**Issue by kevenv** [wolfpld/tracy#1]
Hi, I had to install capstone via vcpkg to build on windows 10 with visual studio 2019.
`vcpkg.exe install --triplet x64-windows-static capstone`

**Comment by wolfpld** [comment]
Yes, the published manual is relevant to the last stable release, 0.6.3. If you want to use master branch, you will have to rebuild the manual yourself.

To be able to fully utilize capstone you also need to enable support for specific architectures. You can do so by installing `capstone[arm,arm64,x86]`.

This is a common problem, so I will pin this issue for the time being, so that other people can find it easily.
