### ISSUE TITLE
__LINE__ not "constexpr" when using /ZI (edit and continue) on MSCVC

### ISSUE THREAD

**Issue by petersteneteg** [wolfpld/tracy#103]
When using MSVC and having /ZI (edit and continue) enabled, the __LINE__ macro is not a constant se link below
https://developercommunity.visualstudio.com/content/problem/195665/-line-cannot-be-used-as-an-argument-for-constexpr.html

be course of that the recent change in 
https://github.com/wolfpld/tracy/commit/82436049435b7c933212689a62a6ed074a1090b3
makes the build fail. 

Not sure what a good solution would be, I just disabled /ZI I don't really use it any way. But it took a fair bit of time to figure out. Maybe I it would be possible to test it and provide a useful explanation..

**Comment by wolfpld** [comment]
The C++11 spec states that `__LINE__` is an integer constant:

```
__LINE__
   The presumed line number (within the current source file) of the current source line (an integer
   constant).
```

And MSDN acknowledges that enabling /ZI makes the compiler non-conformant. I think this might have already been a problem in case of the C API, as mentioned in the appropriate manual section (I don't remember the exact reason why you can't have /ZI and use the C API).

I'm not particularly interested in supporting non-conformant compilers and I don't see a reason why anyone would want to use Edit and continue functionality during profiling. As such, the manual has been updated in c243ac5c.

Thanks for spotting this.

**Comment by stgatilov** [comment]
For game development, both Debug build performance and Edit and Continue matter. Although if there is a performance problem in Debug build, then I suppose other tools are usually enough.

It's not entirely useless, but not very important either.

**Comment by stgatilov** [comment]
Just caught another problem with constexpr, which shows that "must be pointer to const memory / string literal" is significantly less restrictive than "string must be compile-time constant".

Doom 3 has "decl files" of different types: material, sound shader, animation, entity def, etc.
I want to create a zone for decl file parsing, but I'd like to set zone name depending on the type of decl file, i.e. "Parse:Material", "Parse:Sound", etc.

Parsing of a decl file starts in a single function regardless of its type. The type is available integer/enum value in this function. I can easily create a constant array with string literals, and select one at runtime element by indexing it:

```cpp
const char *NAME_DECL_TYPE[] = {"Parse:Material", "Parse:Sound", ...};
...
void idDeclLocal::ParseLocal( void ) {
   ...
   ZoneNamed(NAME_DECL_TYPE[this->type], true);
   ...
}
```
But I cannot find any way to make this constexpr.

I guess I'll have to choose between patching headers and using C API in this case.

**Comment by wolfpld** [comment]
The source location of any zone is stored just as a pointer to a data structure, which holds all the required information, such as the file, or function name. This structure is then retrieved by the profiler at an unspecified time.

You are not passing the source location data for immediate consumption within the `Zone...` call, but are declaring that this data will be accessible at a specific location, when required. As such, you cannot make the zone name dynamic.

In your use case you may employ one of the following options:
1. Use `ZoneScoped`, and then an additional `ZoneName` (without the `d` at the end) call. This name will be displayed by the profiler in the thread lanes, but the original function name (`idDeclLocal::ParseLocal`) will be used for statistical purposes.
2. Alternatively you may use `ZoneTransientN` macro (I think I will rename it to `ZoneDynamic`, for better discoverability), which will internally allocate a new source location structure for each call. This allows you to have fully dynamic names, at the cost of additional perf and memory requirements.

**Comment by stgatilov** [comment]
I'm sorry, but I have written wrong reproduction code.
We wrapped Tracy macros into our own, and I did the back conversion incorrectly.
I have just edited the code above: we actually use `ZoneNamedN` macro.

My problem is about zone name, not about source code location.

**Comment by wolfpld** [comment]
It doesn't change much, as the `Zone...` macro family stays the same. The difference between `ZoneNamed` and `ZoneNamedN` is just that one field in the source location data struct is nullptr, or not.

> My problem is about zone name, not about source code location.

This is the same problem.

**Comment by stgatilov** [comment]
Also, I think that in the sample code, the passed string would be available at any moment, since `NAME_DECL_TYPE` is a global array with initialization.

Alternatively, it can be done without global array like this:
```cpp
const char *NameOfDeclType(int type) {
  if (type == TYPE_MATERIAL) return "Parse:Material";
  if (type == TYPE_SOUND) return "Parse:Sound";
  ...
}
...
void idDeclLocal::ParseLocal( void ) {
   ...
   ZoneNamedN(__var_somename, NameOfDeclType(this->type), true);
   ...
}
```
Once again, the passed string is available at any moment, but is not compile-time constant.

**Comment by wolfpld** [comment]
The `ZoneNamedN( zoneVar, "Parse:Material", true )` macro is expanded by the preprocessor to, let's say:
```c++
static constexpr tracy::SourceLocationData __tracy_source_location2149 {
    "Parse:Material",
    "idDeclLocal::ParseLocal",
    "framework/DeclManager.cpp",
    2149,
    0
};
tracy::ScopedZone zoneVar( &__tracy_source_location2149, true );
```

The source location data structure is created at compile time and is stored in a read-only executable image segment. The profiler is able to reference this memory, and the strings contained within.

What you are asking here is to either:
1) make this static data structure be created/selected depending on some run-time variable,
2) or to make the contents mutable during the program execution. This would break the "can be retrieved at any time" rule.

The language gives you some ways to achieve what you want, for example with use of templates, which will create a number of instances of your function, each with its own static source location structure. Of course, you will have to add some kind of dispatch, so that each template variant can be properly accessed.

Alternatively, you may use the two originally proposed options, which do exactly what you expect.

**Comment by stgatilov** [comment]
Thank you!
Now I finally understand what's wrong with my ideas. I thought that string pointers were stored individually in memory. If the pointer to static struct is saved, then indeed it has to be compile-time constant.

I looked into transient zones, but somehow understood that they only allow to configure source code location but not name. Perhaps because the corresponding section in the manual says only: **In order to prevent problems caused by unloadable code, described in section 3.1.1, transient zones copy the source location data to an on-heap buffer**.

I tried it now, and it works perfectly.
All the three strings together usually take about 100 bytes, and given that our largest level generates about 16K zones in total, those additional 2 MB of data are negligible compared to a typical trace size.

**Comment by wolfpld** [comment]
> All the three strings together usually take about 100 bytes, and given that our largest level generates about 16K zones in total, those additional 2 MB of data are negligible compared to a typical trace size.

BTW, this is only a client-side and network cost. On the server the source location data is properly deduplicated.
