### ISSUE TITLE
Add tracy to vcpkg

### ISSUE THREAD

**Issue by s9w** [wolfpld/tracy#113]
I think it would be cool to import the library part of tracy from vcpkg. They don't add packages themselves - they only accept if someone writes the pull request. Tracy [was actually requested there a while ago](https://github.com/microsoft/vcpkg/issues/9269).

Feel free to close this is this is unwanted.

**Comment by wolfpld** [comment]
I'm not particularly interested in doing this at the moment, but I will leave the issue open, as someone might want to do this.

**Comment by Spirrwell** [comment]
[tracy.zip](https://github.com/wolfpld/tracy/files/7134450/tracy.zip)

I've made and attached a vcpkg port for tracy version 0.7.8. You should be able to either plop this into your vcpkg's "ports" folder (I don't recommend doing that in the event it's ever merged into the vcpkg repo) or you can use vcpkg's --overlay-ports=path/to/custom/ports

It's configurable with Tracy's features so you could do `vcpkg install tracy[callstack,on-demand]`

You can check the vcpkg.json or do vcpkg search to see all of their names.



This is my first attempt at a vcpkg port and it's definitely not perfect. The actual vcpkg portion seems mostly straightforward. I had a bit of difficulty understanding the CMake end, making it usable with find_package() and such.

0.7.8 does not have a CMakeLists.txt, this port contains a modified version of the CMakeLists.txt that's on the repo right now. If you use the port as is, it will pull 0.7.8 and copy the CMakeLists.txt to it for vcpkg to build/configure it.

The most notable changes to the CMake script that might be worth merging into master are as follows:

- target_include_directories uses the BUILD_INTERFACE and INSTALL_INTERFACE generator expressions to setup the include dir for the installed package
- target_link_libraries makes Threads::Threads PRIVATE so end-users don't have to find_package(Threads) 
- I added ${scope} to the set_option macro so that TRACY_ENABLE is PRIVATE while all others are PUBLIC. The PUBLIC options/compile definitions will propagate when the end-user links against tracy
- I check if BUILD_SHARED_LIBS is set and add PRIVATE and INTERFACE compile definitions for TRACY_EXPORTS and TRACY_IMPORTS
- Install files/export config

As far as the INSTALL_INTERFACE include goes, I think other libraries export a config which substitutes paths somehow, but that's a bit over my head at the moment. I just set it to "include" for vcpkg for now. The install commands for the headers also use the "include" destination. Again, I don't think this is how it's supposed to be done, but for vcpkg it works.

I also added a TRACY_VERSION variable for TracyClient, but I also am not familiar with how the versioning works when exporting a config for find_package() to use.

That's about it. I could try doing that pull request that NancyLi1013 wanted in that issue. Though I'd prefer people try it out first and make sure it works well.

**Comment by wolfpld** [comment]
https://github.com/microsoft/vcpkg/pull/21826
