### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by maidamai0** [wolfpld/tracy#120]
#### 🐛 Issue

When clicking **messages**, **Tracy Profiler** takes a very long time to respond.

![image](https://user-images.githubusercontent.com/16829798/97663522-ca930400-1ab4-11eb-84ef-d6ea9c9516a6.png)

#### ℹ️ Plantform 

* OS: window 10 20h2
* compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29112 for x64

**Comment by wolfpld** [comment]
Do you have a trace that you can share?

**Comment by maidamai0** [comment]
I just saved a copy of my trace data.
[no_respond_on_messages.zip](https://github.com/wolfpld/tracy/files/5473136/no_respond_on_messages.zip)

**Comment by wolfpld** [comment]
How do you define "a very long time"? Are you using a debug build?

**Comment by maidamai0** [comment]
It takes several seconds on my machine with i7-4800MQ 16GB RAM and yes, I use it in a debug build.
I tried again with a release build and it takes less than 1 second. I can close this if this is not an issue for you.

**Comment by wolfpld** [comment]
Please don't use debug builds for real work.

The reason "going to message" is slow is that all the messages on the list have to be rendered (twice) in such instance, in order to be able to properly set message list scroll offset. This is a limitation of `ImGuiListClipper`. I believe @ocornut is aware of the issue and plans to overhaul the clipper implementation at some point in the future.
