### ISSUE TITLE
Sampling on Android: few samples and no asm view.

### ISSUE THREAD

**Issue by bjacob** [wolfpld/tracy#125]
Attached a `.tracy` trace saved from the Tracy profiler UI: [low-samping-freq-and-no-asm.tracy.zip](https://github.com/wolfpld/tracy/files/5556324/low-samping-freq-and-no-asm.tracy.zip)

**What looks like not working as intended:**

1. I can't see a disassembly view, only a C++ source view.

2. There seem to be few samples in here. Most 'source views' don't show any "time percentage" left margin. Those that do have a "time percentage" left margin tend to have only few samples, as in the attached screenshot which says 3 samples.

3. It keeps saying '0x0' in the line at the top of the source view, as if it couldn't read a symbol address (?), see screenshot below.

<img width="715" alt="Screen Shot 2020-11-17 at 4 29 57 PM" src="https://user-images.githubusercontent.com/79535/99453008-4cc35b00-28f2-11eb-8ac4-57aded0a7992.png">

**Details about the workload:**

Upon request I could try to share steps to reproduce that trace, but that would be a bit complex. The workload is a neural network inference using [IREE](https://github.com/google/iree). This is running on a Pixel4 Android 10 device, the CPU architecture is aarch64.

The workload is Tracy-instrumented as follows: source: [tracing.h](https://github.com/google/iree/blob/main/iree/base/tracing.h), [tracing.cc](https://github.com/google/iree/blob/main/iree/base/tracing.cc) .

Regarding the "no asm view" part of this issue, a relevant fact about this workload might be that it involves code compiled by direct usage of LLVM , not compiled from a C or C++ source.

@benvanik has had complete success with Tracy with the same workload but running on Windows. So if the problem is on our end then it has to be somehow in a part of our code that's different on android vs windows (?)

**Comment by benvanik** [comment]
Likely two separate issues here; one is the 10ms sample interval, the other is how (or if) source mapping works on Android or if there's some special build configuration required (to avoid symbol stripping/etc that tracy may be relying on). If it's expected that the sample rate is higher on Android and that the asm view works then that indicates we are doing something wrong.

There's nothing that stands out to me in the UI from your trace (in that, info -> trace statistics doesn't show any sampling related information that may indicate the desired/actual sampling interval?) - that may be the feature request here to help people self-diagnose :)

As for the asm, I'm unfamiliar with how tracy + elf + android + etc works enough to know the expected flow. For example, is the tracy profiler UI looking for symbols (by peeking inside an elf with embedded dwarf) on the host machine when displaying the code, or is the debug info cached along with the sources during capture? (I don't see anything related to symbols in the info -> trace statistics - like I do with source code - so that may be another useful thing to help people self-diagnose things like missing symbols)

The thing that stands out to me with the symbols is the 0x0 here: 
![image](https://user-images.githubusercontent.com/75337/99454900-eb908d00-28db-11eb-95ad-fb512578567d.png)
if we knew how/when that binary was being touched then it may be the issue - it may be looking on your host machine running the UI for /data/local/tmp.... and not finding anything, as expected :)
This may need something like a the source file mapping but for binaries - unless that's already supported.

@bjacob: can you make a /data/local/tmp/ on your host and copy the binary there to see if you get non-0x0 addresses? if so, that confirms that. It may mean adding a feature where binaries can be cached like source files so that resolution can happen after the fact.

**Comment by wolfpld** [comment]
The sampling rate (100us) is fine - that's 10 kHz*. The call stack data is also properly received - click on any of the sampling dots to see that there are proper function names, inline resolution and symbol addresses are present. This should be everything that is needed for the symbol code fragments to be received, but they aren't.

Code retrieval is actually done is a very simple way that will work regardless of the way code was generated or where it is on the disk. Each symbol ("function") has to be present in memory at some address to be executed and the symbol size is also known in the debug info. This makes the task of code retrieval a simple `memcpy` to a buffer, which is then sent to the server.

I think the real issue here is that the trace is somewhat short (2 seconds) and the application seems to be terminated without allowing retrieval of missing data by the server. This can be seen as "???" zones at the end of main thread, and also unresolved stack frames in the same place, e.g.:

```
  0. memset + 172  ([unknown]) /apex/com.android.runtime/lib64/bionic/libc.so
  1. 000000605B4F5DAC
  2. 000000605B4F6138
  3. 000000605B4FB56C
  4. 000000605B46CCDC
inl. iree::vm::ref<iree_hal_command_buffer>::get() const  (/usr/local/google/home/benoitjacob/iree/iree/vm/ref_cc.h:191) /data/local/tmp/iree-benchmark-module
inl. iree::vm::ref<iree_hal_command_buffer>::~ref()  (/usr/local/google/home/benoitjacob/iree/iree/vm/ref_cc.h:128) /data/local/tmp/iree-benchmark-module
(...)
```

When the application is terminating (by returning from `main()`), the profiler shouldn't exit until all the needed data is transferred. This is done by waiting in the profiler's destructor. Forcibly exiting the application, for example by using `exit()`, or maybe by some external interference (android's activity exiting?) will break things. You should investigate what's happening there.

*) Most of the sampled call stacks in the "cpu0" thread have an unresolved frame at the top, e.g.:

```
  0. 00000077011FB9B8
inl. iree::Status::code() const  (/usr/local/google/home/benoitjacob/iree/iree/base/internal/status.h:177) /data/local/tmp/iree-benchmark-module
inl. iree::IsOk(iree::Status const&)  (/usr/local/google/home/benoitjacob/iree/iree/base/internal/status.h:231) /data/local/tmp/iree-benchmark-module
(...)
```

The top frame is also the instruction pointer, so without knowledge about the frame, there's no possibility to properly assign it to the appropriate code location. This explains why you're seeing very small number of samples in the source view.

**Comment by bjacob** [comment]
Thanks a lot for the insight about the real issue likely being about the premature application termination. It's true that I terminate the application with Ctrl+C... I'm running it with TRACY_NO_EXIT=1 so I didn't question having to Ctrl+C, but rereading the manual I now understand that I shouldn't have to, after the Tracy UI has connected.

On the Tracy UI side, I see the satellite dish icon stays on forever, and when I hover over it, the tooltip says: "Queries in flight: 900".

It stays like this forever. The data transfer stats in the top-left connection window don't change either.

If I strace the Tracy UI process, stuff seems to be happening - lots of recvmsg, some of them succeeding, others failing with EAGAIN. Its doesn't look stuck as far as strace can see.

If I strace the client (Android) process, ... suddenly it's unstuck, finishes the transfer quickly , but then in the Tracy UI there is no Sampling data.

The fact that strace'ing the client process makes an observable difference made me think it might be a race condition (how else could strace make an observable difference?) but i haven't been able to prove it. If it's a race then it's not a race local to the server process, because the server process runs fine with ThreadSanitizer.  (I can't try ThreadSanitizer on the client process because of https://github.com/android/ndk/issues/1171 ).

**Comment by bjacob** [comment]
In a debug build, the server (UI) fails [this assertion](https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/server/TracyWorker.cpp#L5525). If I comment that assertion out, no other assert fails.

Is this assertion failure relevant?

**Comment by wolfpld** [comment]
> On the Tracy UI side, I see the satellite dish icon stays on forever, and when I hover over it, the tooltip says: "Queries in flight: 900".
> It stays like this forever. The data transfer stats in the top-left connection window don't change either.

Tracy has to keep track of the server -> client socket buffer size to prevent situations where both sides of the connection hang waiting for the other side to receive data (which can't be done, because both sides are waiting for each other). It is possible that there are some logic errors in this tracking.

That being said, with 900 unaccounted queries (this typically is well below the send window size) you should have all the required data anyway. It this true in your case? You can check for "???" zones or unresolved frames in call stacks to see if not.

> If I strace the client (Android) process, ... suddenly it's unstuck, finishes the transfer quickly , but then in the Tracy UI there is no Sampling data.

I'd say this is due to interference of `strace` with `su`.

> In a debug build, the server (UI) fails this assertion. If I comment that assertion out, no other assert fails.
> Is this assertion failure relevant?

Not really. When it fires it only affects how samples are selected when time range of statistics is limited. This is eventually fixed after saving and reloading the trace: https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/server/TracyWorker.cpp#L1756-L1757.

**Comment by bjacob** [comment]
Thanks for the replies.
* Good point about the interaction with `strace` and `su`, that's probably it.
* There are no "???" or unresolved frames in call stacks, so the trace looks complete besides the strangely low samples count, no asm view, 0x0 symbols and satellite dish icon. Also if I hit Ctrl-C in the client, the profiler shows a dialog saying it lost connection with the client and the trace will be incomplete.

I have started to debug around `TracySocket.cpp`...  after initial activity, once it looks stalled, it's reached a steady state where:
* The server (profiler UI) gets `poll` timeouts in `Socket::Recv`. Specifically, this `poll` returns `0` once we have reached the stalling steady state (and that does not happen before that stalling while actual data transfer occurs): https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/common/TracySocket.cpp#L345
* The client (Android) does not see anything wrong happening, not even a socket timeout (once the profiler UI has connected). In the stalled steady state, nothing at all seems to be happening in the client in `TracySocket.cpp` logging.

I didn't see any error (no syscall returned -1) on either side.

So... does this look like the server is waiting for the client to communicate and the client doesn't realize it's supposed to be communicating?

**Comment by bjacob** [comment]
The client (Android) is stuck here, in `HandleServerQuery()`: https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/client/TracyProfiler.cpp#L1537

**Comment by bjacob** [comment]
Got it!
HandleServerQuery calls `HandleSymbolCodeQuery` here, https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/client/TracyProfiler.cpp#L2516. This ends up in `AppendDataUnsafe` performing a `memcpy` here,
https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/client/TracyProfiler.hpp#L651

This `memcpy` segfaults. It wasn't readily obvious because that's handled by a signal handler by Tracy, and it ends up stuck in this loop waiting for shutdown: https://github.com/wolfpld/tracy/blob/37c9a5807f7743d6b13e827907c32a3d9d67a989/client/TracyProfiler.cpp#L861

It became obvious in GDB, but out of laziness (GDB on Android is not a great experience) I stuck with printf-debugging for too long before switching to GDB.

Why does this memcpy segfault? The address ranges being accessed are valid, but looking up `/proc/<pid>/maps`, the source range is executable, not readable:
```
7adb1fa000-7adb29b000 --xp 00042000 07:48 35                             /apex/com.android.runtime/lib64/bionic/libc.so
```

OK so it looks like I should be able to get out of the deadlock by defining `TRACY_NO_CODE_TRANSFER` . But IIUC that will disable exactly the asm view that I was hoping to obtain....

**Comment by wolfpld** [comment]
> Why does this memcpy segfault? The address ranges being accessed are valid, but looking up /proc/<pid>/maps, the source range is executable, not readable:

Interesting. Currently there's assumption that all memory pages are readable.

The way to proceed here would be to examine the process memory map and then change the protection using `mprotect()`.

**Comment by bjacob** [comment]
Running into a snag with that: just indiscriminately calling `mprotect` in `AppendDataUnsafe`, trying a few different permissions until one works, like this,

```
        for (auto perm : {PROT_READ, PROT_READ | PROT_EXEC, PROT_READ | PROT_WRITE, PROT_READ | PROT_WRITE | PROT_EXEC}) {
            fprintf(stderr, "attempting mprotect on aligned_start_address=%p aligned_len=%llu\n", aligned_start_address, aligned_len);
            if (mprotect(reinterpret_cast<void*>(aligned_start_address), aligned_len, perm) == 0) {
                fprintf(stderr, "SUCCESS success on aligned_start_address=%p aligned_len=%llu\n", aligned_start_address, aligned_len);
                break;
            }
        }
```

Actually segfaults on the first attempt:

```
attempting mprotect on aligned_start_address=0x7873d8b000 aligned_len=4096
Segmentation fault 
```

The mapping is
```
7873c95000-7873d90000 rw-p 00000000 00:00 0                              [anon:stack_and_tls:10574]
```

Since `mprotect` segfaults instead of just returning an error code, we have a few options...
1. Is there a "read" converse to `mprotect`, allowing to query page permissions? (I couldn't find one)
2. We could parse `/proc/self/maps`
3. We could install another signal handler.

Going to try 2. by default, please let me know if you have any other advice!

**Comment by wolfpld** [comment]
`AppendDataUnsafe` is not the right place to do this. You can see from the memory map data that you are trying to modify stack/tls data, which does not contain executable code.

The proper way to do this is to enumerate mappings using `/proc/self/maps` (due to lack of a better interface) to find which memory range, and if, needs to have its permissions changed (by checking the permissions already present in `/proc/self/maps`, and adding read flag), in some sort of handler called from `Profiler::HandleSymbolCodeQuery()`.

There should be some kind of caching scheme, to reduce cost of re-parsing `/proc/self/maps`. Something similar to `ModuleCache`/`s_modCache` in `TracyCallstack.cpp`.

**Comment by bjacob** [comment]
OK, i've checked that `mprotect` succeeds making these exec mappings readable.

Should we restore mapping permissions once we're done?

Should we strictly try to only do this to mappings that we really need to (as run into by HandleSymbolCodeQuery)?

If it's OK to just make all executable mappings readable, that can be done in a much simpler way as in that case we don't need a new data structure and caching mechanism.

**Comment by wolfpld** [comment]
> Should we restore mapping permissions once we're done?

I don't think this will be needed, and it's also not really possible to know when the retrieval process is done. Code transfer can be requested at any time.

> Should we strictly try to only do this to mappings that we really need to (as run into by HandleSymbolCodeQuery)?

Yes.

> If it's OK to just make all executable mappings readable, that can be done in a much simpler way as in that case we don't need a new data structure and caching mechanism.

New mappings can appear at any time, for example when a library is dynamically loaded. Tracy has to be able to react to such changes.

**Comment by bjacob** [comment]
OK, PR #129 is up!
