### ISSUE TITLE
Bad culling when rendering GPU Zones in Profiler

### ISSUE THREAD

**Issue by GenuineAster** [wolfpld/tracy#141]
When navigating GPU zones, they don't seem to cull properly (see attached gif).

I am experimenting with my own TracyVulkan implementation, so it might be my fault? But I'm not sure how or why.

![tracy_gpu_zones](https://user-images.githubusercontent.com/57984334/100734037-57d8b980-33cf-11eb-8b15-59e8c569e6bf.gif)

**Comment by wolfpld** [comment]
What you're seeing here is caused by Vulkan zones not being properly sorted by time. This breaks rendering, which is using binary search to find zone range to draw.

On the client side, Tracy expects that a series of `vkCmdWriteTimestamp()` calls (or similar, in other APIs) will produce monotonically increasing time stamps. Whether this is true or not is solely dependant on the underlying graphic API implementation and vendor drivers. In my understanding, the GPU timestamp API was designed to measure how long some draw commands took (i.e. for benchmarking), and not to provide a consistent long-term evaluation of execution, which Tracy is trying to do. As a consequence, this use pattern may not be well tested in drivers. This is also the reason why GPU zones are quite bare with features in comparison to CPU zones, as you have noticed in #140.

I'm not sure there can be anything done about this (and I've tried).

**Comment by GenuineAster** [comment]
Ok, I read what you wrote a bit more carefully and tried to sort all GPU zones by start time every frame on the Tracy client before submitting them and that made everything much better! I guess this ticket should stay open nonetheless?

**Comment by GenuineAster** [comment]
Also worth noting that despite the problems you pointed out with GPU timestamp APIs, it seems to be doing really well for helping us estimate what is taking time in our rendering pipeline, so the usecase is totally valid for us.

**Comment by wolfpld** [comment]
> I guess this ticket should stay open nonetheless?

I'm not sure. Are there any actionable items here?

**Comment by GenuineAster** [comment]
Hm.. I guess some documentation somewhere would be nice, even though there isn't really much docs for writing your own Tracy "extensions"

**Comment by wolfpld** [comment]
> I guess some documentation somewhere would be nice, even though there isn't really much docs for writing your own Tracy "extensions".

Can you specify what you would like to have documented here?

> Fixing the way the Tracy server culls zones would be the ultimate fix, but I guess that's not really possible nor easy to motivate given the use case.

It may be possible to enforce proper zone order by sorting the zone vectors (e.g. post capture), but if you have out-of-order zones, then you probably also have mismatched zone begin and end events, which would be unfixable.
