### ISSUE TITLE
Performance: Span overhead is ~29ns

### ISSUE THREAD

**Issue by sujayakar** [wolfpld/tracy#192]
Hello! I'm working on a microsecond scale application in Rust where Tracy would be invaluable for debugging performance issues. I'm working on my fork of `rust_tracy_client` [here](https://github.com/sujayakar/rust_tracy_client), where I have a test application that logs 10M spans in 293ms (for an average of 29ns/span):
```
~/src/rust_tracy_client/tracy-client $ cargo run --example static --release             
    Finished release [optimized + debuginfo] target(s) in 0.01s
     Running `target/release/examples/static`
Logged 10000000 spans in 293.115409ms (29ns per span)
```
Of course, 29ns per span is amazing, but the manual states in Section 1.7 that we should be able to get to a few ns per span and walks through the assembly. My Rust example's disassembly has some peculiarities due to a lack of cross-language inlining, so to minimize this to a smaller test, I wrote a C program.
```C
//  c++ -g -O3 -flto -march=native -DTRACY_NO_VERIFY -DTRACY_ENABLE TracyClient.cpp test.c -lpthread -ldl
#include "TracyC.h"
#include <time.h>
#include <stdio.h>

int main(int argc, char** argv) {
  ___tracy_init_thread();

  struct timespec start;
  if (clock_gettime(CLOCK_MONOTONIC, &start) != 0) {
    perror("clock_gettime failed");
    return 1;
  }

  int n = 10000000;

  for (int i = 0; i < n; i++) {
    struct ___tracy_source_location_data s;
    s.name = "amazing trace";
    s.function = "main";
    s.file = "test.c";
    s.line = 13;
    s.color = 0;

    TracyCZoneCtx c = ___tracy_emit_zone_begin(&s, 1);
    ___tracy_emit_zone_end(c);
  }

  struct timespec end;
  if (clock_gettime(CLOCK_MONOTONIC, &end) != 0) {
    perror("clock_gettime failed");
    return 1;
  }

  double duration = end.tv_sec - start.tv_sec;
  duration += end.tv_nsec * 1e-9;
  duration -= start.tv_nsec * 1e-9;

  printf("Logged %d spans in %0.4fms (%fns per span)\n", n, duration * 1e3, duration / n * 1e9);
  return 0;
}
```
Sure enough, I see similar results of ~28ns/span on my machine. I changed the loop to run indefinitely and from watching it in `perf top`, it looks like the `rdtsc` instruction is taking up ~70% of the program's total time.

I'm running an AMD Ryzen 9 3950X with gcc 9.3.0. Perhaps there's some AMD-specific microarchitectural issues at play here? What was the test setup for the numbers in the manual?

**Comment by wolfpld** [comment]
Tracy already does an equivalent of your empty zone begin+end loop. This is available as "queue delay" e.g. in trace information window.

The measurements, as described in the manual, do not represent this value, but rather a real wall-clock impact on program execution time (the exact way of calculating this is explained in the manual). The test was done on i7-8700K with MSVC. Due to the way out-of-order CPUs execute code, the "queue delay" self-measurement may not reflect the true performance impact, which in this case was actually smaller.

Here are some measurements of the "queue delay" performed on various CPUs and compilers:
i7-8700K, MSVC: 9 ns
i5-8259U, gcc: 20 ns
Ryzen 3900X, MSVC: 10 ns
Ryzen 3900X, gcc: 20 ns
Ryzen 5950X, MSVC: 9 ns

As you can see, the CPU model has negligible impact, even if we're comparing the monolithic Intel CPUs with AMD CPUs that use separate chiplets. The actual cause here is the compiler (and OS) used to prepare the program. I believe this can be explained by differences in the conventions of retrieval and initialization of the TLS block.

Moreover, there _are_ discrepancies in how Intel and AMD report values at the hardware level.

Intel:
![obraz](https://user-images.githubusercontent.com/600573/113280923-3a681d80-92e5-11eb-9a9f-1033d89ff5a1.png)

AMD:
![obraz](https://user-images.githubusercontent.com/600573/113280961-4653df80-92e5-11eb-8349-a871f66f3f64.png)

The lower resolution of measurements on AMD was explained to me as follows: "The TSC implementation is quite tricky with the requirements that it be synchronous across all threads which includes the two sockets in a server system as well as counting at the same frequency through all the power states and frequency changes. So yes, the resolution is 10 nsecs as you have measured."

**Comment by sujayakar** [comment]
Very cool, and thanks for the response! Sorry for not reading the manual closely enough -- it's clear to me now what Section 1.7 is measuring, and that number makes more sense for impact on a real application than the synthetic loop.
