### ISSUE TITLE
Assert in Worker::ProcessGpuZoneEnd

### ISSUE THREAD

**Issue by ataulien-thqnordic** [wolfpld/tracy#263]
Hi! We're currently trying to integrate Tracy into our engine and it has been going well so far. However, we are having issues with the GPU-Zones (D3D11). In our Editor they work fine and we can see them inside the TracyServer, however, as standalone Game the _TracyServer_ crashes on an assertion. (Game continues running)

I'm sure we are probably missing something on the integration, but since it's not our engine that is crashing but the TracyServer, we are a bit lost on how to go further.

The assertion that trips is here, in `Worker::ProcessGpuZoneEnd`:
https://github.com/wolfpld/tracy/blob/058e89011fceca912d43638ebb6b85992147fcfe/server/TracyWorker.cpp#L5641

The assert is triggered with the latest official release 0.7.8 and the latest master. 

If you need any more information, please let me know!

**Comment by wolfpld** [comment]
Capturing zones in Tracy is done without keeping track of the state. The profiled application emits "zone begin" and "zone end" events, but it does not check if the sent data is valid in any way. The zone end events are matched to proper zones (created by zone begin events) by keeping track of a zone stack on the server.

The assert you are seeing indicates that some zone has just ended, but its corresponding zone begin event was never received by the server. This may also happen if you double-free a zone. While the effects of this are seen on the server, the root cause is in the profiled application.

I'd suggest taking a close look at how you manage the `tracy::D3D11ZoneScope` scope, as the failing events indicate that actions taken in the ctor and/or dtor of this structure are the cause.

**Comment by ataulien-thqnordic** [comment]
Thanks for the quick response! We indeed had to manage the lifetime of the `tracy::D3D11ZoneScope` objects on our own to use it within existing Push/Pop-functions. 

In our tests we put breakpoints into all the constructors/destructors of `tracy::D3D11ZoneScope` and the behavior looked fine. We will keep looking further into this, thanks for the insight!

I assume all begins/ends need to be available once `TracyD3D11Collect` is being called or does that not matter? 

If we miss one begin at the very start of the program and then attach Tracy later, I assume that would also cause the assertion, since the client will send over everything it has gathered over to the Server, right?

**Comment by wolfpld** [comment]
> I assume all begins/ends need to be available once `TracyD3D11Collect` is being called or does that not matter?

The timestamp query is issued to the GPU right before the zone begin/end event is queued for transfer in the ctor/dtor, along with the returned query id. This id is then used to match the queries collected in the `Collect` functions to the appropriate events. Therefore it shouldn't be possible for `Collect` to have a query response for a zone which is not known to the server.

> If we miss one begin at the very start of the program and then attach Tracy later, I assume that would also cause the assertion, since the client will send over everything it has gathered over to the Server, right?

If you are using the on-demand mode, the begin/end events should be balanced through the `m_active` early exit functionality. That is, the end events won't be reported for zones which have not reported the begin events.
