### ISSUE TITLE
Compilation error with capstone 5.0_rc2

### ISSUE THREAD

**Issue by u3shit** [wolfpld/tracy#429]
Trying to compile the profiler fails because it can't find `capstone.h`.  I have 5.0_rc2-r1 installed from gentoo linux, which installs a pc file:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: capstone
Description: Capstone disassembly engine
Version: 5.0.0
URL: http://www.capstone-engine.org
archive=${libdir}/libcapstone.a
Libs: -L${libdir} -lcapstone
Cflags: -I${includedir}
archs=
```
i.e. it will only have `/usr/include` in the include dirs, but I only have `/usr/include/capstone/capstone.h`. This is different from capstone 4.0.2, which had `/usr/include/capstone` as an includedir, so a single include of `<capstone.h>` worked there.

**Comment by wolfpld** [comment]
In-development versions of libraries (which a RC is) are not supported.

**Comment by u3shit** [comment]
Alright, but in that case the manual shouldn't suggest using the `next` branch of capstone when it has the same pc file: https://github.com/capstone-engine/capstone/blob/next/capstone.pc.in

**Comment by wolfpld** [comment]
This is a fairly recent change: https://github.com/capstone-engine/capstone/issues/1807, and an intended breakage. I'm not sure what is your expectation here. I will not be performing daily checks if each library in use have possibly broken something in their development versions.

**Comment by u3shit** [comment]
I just wanted to report a bug :(

**Comment by wolfpld** [comment]
The real problem here is that capstone fails to produce a new release, keeping the current RC in limbo for almost half a year now.

**Comment by indirectlylit** [comment]
I also ran into this issue while trying to build Tracy as a new user. Leaving some notes here in case it helps others.

Using the HEAD of the `next` branch worked last year but no longer works because (as mentioned above) in https://github.com/capstone-engine/capstone/commit/6656bcb63ab4e87dc6079bd6b6b12cc8dd9b2ad8 the include path was changed. 

The [parent commit](https://github.com/capstone-engine/capstone/commit/e4965783cfb30c12ae8f1b7bbce446fef03e2b68) seems to work though:


```bash
git clone https://github.com/capstone-engine/capstone
cd capstone
git checkout e4965783cfb30c12ae8f1b7bbce446fef03e2b68  # last working commit on next branch
```

After building and installing, capstone.pc will define the `includedir` as `/usr/local/include/capstone` and Tracy should be able to find `capstone.h`.

Alternatively – as I eventually realized 🤦 – the `4.0.2` stable/unmaintained/deprecated release seems to work fine for my purposes.

> In-development versions of libraries (which a RC is) are not supported

@wolfpld - I personally read the Tracy docs as suggesting the `next` branch as the default because the Capstone `master` branch is described as unmaintained and deprecated. While Tracy docs and code definitely shouldn't need to be kept up-to-date with Capstone's unstable branch, it might help other Tracy newcomers if the docs encouraged using 4.0.2 as the default choice if that is considered more likely to succeed.
