### ISSUE TITLE
Memory grows quickly when profiler is attached

### ISSUE THREAD

**Issue by theWatchmen** [wolfpld/tracy#507]
I am using Tracy compiled as a static library, which is then linked to each project using it. This is done through CMake. Everything works fine, but when I attach the profiler, the memory used by the application starts growing rapidly. The profiler is reporting several GBs of memory in use after a few seconds of profiling. The app only has a few zones active. Once I stop the profiler the memory stops growing but it stays high, even after I close the profiler.

I haven't had this problem before, so it's likely something to do with the way I am using Tracy for this particular project. The version I am using is 0.7.8 (I think). If it helps, the project uses enkiTS for multi-threading tasks and tlsf for memory allocation.

I tried taking two memory snapshots through VS but couldn't identify what's allocating all that memory.

Any suggestions as what the root cause could be? Any more details I should provide to help with the investigation?

**Comment by wolfpld** [comment]
Update to the latest version and re-verify.

**Comment by theWatchmen** [comment]
Done :) Updated to latest 0.9 version. The memory grows more slowly, but still reaches a few GBs after a few seconds:
![image](https://user-images.githubusercontent.com/7221779/210782615-d0aa3ed9-9e1c-490c-9625-b3208b4c02fd.png)

**Comment by wolfpld** [comment]
Can you specify where do you see this memory growth?

**Comment by theWatchmen** [comment]
This a a snapshot from Visual Studio (from a debug build of tracy):
![image](https://user-images.githubusercontent.com/7221779/211286398-2967ec48-3c25-4280-909d-1ff5727f78e7.png)

I couldn't figure out how to save the heap snapshot :(

When I build the tracy client in my application, I have the following flags specified:
```
TRACY_ENABLE
TRACY_ON_DEMAND
TRACY_NO_SYSTEM_TRACING
```

As a test, I tried compiling the tracy client directly into the main executable but the memory behaviour doesn't change.

**Comment by wolfpld** [comment]
The memory usage you see on the server is caused by something you are collecting client-side. To pinpoint what it is, refer to a rough outline of collected events, which can be seen in the trace statistics section of the trace information window.

The memory growth you see on the client is caused by buildup of collected events that are yet to be sent to the server. Usually this is manageable, but in your case the events are generated faster than they are able to be sent over the network and/or be processed by the server. The memory used to buffer this is never freed, but it will be reused for any future events.

**Comment by theWatchmen** [comment]
Apologies for the delay, I managed to get to look at this only today! Thanks for your help, after looking at the trace statistics I saw one zone with a count 27M. Turns out I placed a scoped zone in the wrong place which was being called to often.
