### ISSUE TITLE
Security concern: does Tracy access lsass?

### ISSUE THREAD

**Issue by danielbuhrig** [wolfpld/tracy#518]
Hi developpers,

I love using Tracy and it lets me very effectively profile my applications. Good work!
However, I wanted to ask, if Tracy (on Windows) might can cause an access to lsass (Local Security Authority Subsystem Service)? Might be intentionally, might be not.
I'm working in a corporate environment and we have Cybersecurity software installed in order to monitor suspicious behaviour within the corporate network. I recently integrated Tracy in one of my applications and the Cybersecurity software raised a security alert. My application (with integrated Tracy support) made access to lsass and might have accessed windows credentials. My Security Manager is very concered about this behaviour. Is there an explanation to this behaviour? Any way to avoid this access to lsass?

Many thanks for your support already!

**Comment by wolfpld** [comment]
Tracy has the ability to look at what the entire operating system is doing. For example, it can tell you that your application was not running at a particular time because the OS decided to schedule a time slice for another program. Without this information, all you would see is that your application seems to take a lot longer than expected at random places.

Your security department is right to be concerned about this, because system-wide monitoring of which processes start and stop running is not a behavior expected of a typical application. Even getting a list of other programs running at the same time as the application would be worrisome under normal circumstances.

In order to do the things described above, Tracy must request a system-wide profiling privilege from the operating system. This is probably the lsass call you see.

https://github.com/wolfpld/tracy/blob/789f5723321eda340632eaa3cd213d87b3f8b356/public/client/TracySysTrace.cpp#L343-L354

Note that this request will most likely fail if you do not already have administrative privileges.

If this information is not enough to convince your security department, you can use the `TRACY_NO_SYSTEM_TRACING` define to disable this functionality.

**Comment by danielbuhrig** [comment]
Thanks for you quick reply. I thinks `TRACY_NO_SYSTEM_TRACING ` will help me out in the moment.
