### ISSUE TITLE
Profiler crash when client sends TracyAllocS

### ISSUE THREAD

**Issue by slomp** [wolfpld/tracy#568]
Profiler is ending abruptly when client sends TracyAllocS.
This does not happen with Tracy 0.9.1, but is happening on the current `main`.
Client & Profiler host is Windows 10.

**Comment by slomp** [comment]
Callstack, for reference:
![image](https://github.com/wolfpld/tracy/assets/526886/7bfe4ae3-e64c-4549-a9ee-86276c487751)

**Comment by wolfpld** [comment]
It seems that `rMin`, `rMax` and `num` are not initialized here. Initialization is done in `TimelineItemPlot::Preprocess`, which is issued in `TimelineController::End`, and later drawing code is not entered until `m_td.Sync()` finishes, which only happens after all preprocessing is done.

There are some early exit conditions that prevent preprocessing, on the assumption that the results are not needed when the plot is not visible:

```c++
    if( !visible ) return;
    if( yPos > ctx.yMax ) return;
    if( m_plot->data.empty() ) return;
    const auto PlotHeight = int( round( PlotHeightPx * GetScale() ) );
    if( yPos + PlotHeight < ctx.yMin ) return;
```

There is also an early exit within the queued preprocessing function:

```c++
if( vec.front().time.Val() > vEnd || vec.back().time.Val() < vStart ) return;
```

Would you be able to check which early exit check you hit? The last one feels obviously wrong, since the plot *will* be drawn at that point, and it leaves `rMin`, etc. uninitialized. But maybe this is due to some previous check?

**Comment by slomp** [comment]
Yup, it's hitting one of the early-out cases:
```
if( vec.front().time.Val() > vEnd || vec.back().time.Val() < vStart ) return;
```

![image](https://github.com/wolfpld/tracy/assets/526886/be62f211-0d26-4d07-8865-4f8a98cc5a00)

**Comment by wolfpld** [comment]
2b191e15 should fix the problem.

**Comment by slomp** [comment]
Awesome, that seems to have fixed the issue.
Many thanks for the assistance!
