### ISSUE TITLE
'___tracy_scoped_zone': redefinition; multiple initialization

### ISSUE THREAD

**Issue by nielsuiterwijk** [wolfpld/tracy#75]
Hey,

I am looking into integrating tracy into clausewitz, the engine used by all Paradox Development Studio games. It looks very useful, but I ran into the issue where defining a scoped zone multiple times in a function will cause issues. 

I think this can be easily solved by adding the line number to the variable name, the source location already has that. Do you want me to make a pull request?

**Comment by nielsuiterwijk** [comment]
I realize the support functions wouldnt work anymore, not sure if we would use those, or if we should just see it as a limitation and better split up our code in the couple of cases we are running into it

**Comment by wolfpld** [comment]
Sorry, this can't be done as proposed. The source location variable can have line number in its name, as it is used only within the `ZoneScoped` family of macros. Zones created using `ZoneScoped` must have a known name, so that `ZoneText`, `ZoneValue`, ... macros can reference the zone variable to access some internal state. This would be impossible, if the scoped variable name did include line numbers.

Rules for creating multiple zones within one function are described in the manual in section 3.4.2 Multiple zones in one scope.

**Comment by nielsuiterwijk** [comment]
Thanks! I can manage to work around this just fine using the way described in the manual, seems I missed that.
