### ISSUE TITLE
Frames not being marked when running as administrator

### ISSUE THREAD

**Issue by hugoam** [wolfpld/tracy#84]
Hello ! Thanks for the awesome library 😄 
I have encountered a weird issue, where I want to measure context switches, so I'm running the profiled game instrumented with Tracy in administrator mode
The weird thing is that the traces looked fine when I don't do so, but when I do run the game in administrator mode, the frames are not correctly marked anymore, and everything seems to end up in one frame
Do you have any idea what could be causing this ?

Something that might be a clue as to what is up, The main thread instrumentation seems to be completely messed up. Here I don't have anything showing up in the MainThread at the bottom of the image, when usually (when not running as administrator) it's filled with profiling blocks
![image](https://user-images.githubusercontent.com/9502098/89395817-1892a880-d70e-11ea-9d60-ef388c67a839.png)

**Comment by wolfpld** [comment]
Yes, there are some obvious data delivery issues here. The squiggly lines above zone blocks should be more or less contiguous, but they stop being arriving at some point. How much CPU cores do you have and how much threads is your application using?

**Comment by hugoam** [comment]
The machine has 4 physical cores, 8 logical cores, and the application has at least 5 + 5 + 8 + 8 background threads running plus a couple of others (don't ask me why, it's a mess 😢 😄 that's precisely why I'm investigating our threading situation)
I can tweak that number easily to see if has any influence though, I you want me to give that a try

**Comment by wolfpld** [comment]
This might be a problem. Kernel buffers used for context switch capture are ringbuffers and some data can be lost, if the application can't process it quick enough. With this number of threads it's easy to starve the critical processing thread. Even with "well behaved" applications it is possible to run into buffer overflows, as tuning kernel buffer parameters is not that much documented. However, never have I seen it affecting retrieval of normal frame or zone data.

Kernel buffer parameters are set in `TracySysTrace.cpp`:381. The `BufferSize` parameter is already at the maximum (1024 KB). You may want to tweak `MinimumBuffers` and `MaximumBuffers` value, as described at https://docs.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties. Note that this is only a request and the actual obtained value may vary. To check what is really used, inspect the `s_prop` structure after the call to `StartTrace()` (line 399).

I'll see what can be done with adjusting thread priorities, maybe this will help.

> I'm wondering if it can have anything to do with an anticheat software that has been integrated in the game recently

Tracy lives entirely within the profiled process, so that's rather unlikely.

**Comment by hugoam** [comment]
So in short, our context switches situation might be so bad, and involving so many threads, that we pushed Tracy to its limits ? 😄 
The weird thing is indeed how it affects the retrieval of normal frame/zone data, yes. It would be interesting to find or formulate a hypothesis about where this issue comes from.

**Comment by wolfpld** [comment]
I have bumped ETW threads priority in f07eebeb, it should help with the overflows. Let me know if it helps in your case.

> So in short, our context switches situation might be so bad, and involving so many threads, that we pushed Tracy to its limits ? 😄

It's more about how OS handles these things. Tracy is able to handle high data loads (unless you run out of RAM), it just takes some time to transfer everything.

> The weird thing is indeed how it affects the retrieval of normal frame/zone data, yes. It would be interesting to find or formulate a hypothesis about where this issue comes from.

Yes, definitely.

> Another clue that might interest you: when run in administrator mode, so the problematic mode, I only have a few hundreds of megabytes of profiler memory usage (around 250MB), whereas in usual mode it quickly rises to a couple of gigabytes (> 2000 MB very quickly)

This is likely caused by a stall related to symbol resolution. dbghelp.dll is kinda slow with it. You can see that this is happening when queue backlog is high (indicated by the satellite dish icon in the notification area) - the client is slow to respond to symbol requests and as a consequence it's also not sending other data.

**Comment by hugoam** [comment]
Wow, that did the trick ! Amazing, thanks !
It seems I'm still lacking some  symbols, some things now appear as `???`, and you can "feel" the hiccups, the data appears in big gushes, then stalls far a while, but it's altogether much better than before so thanks a lot 😄 
![image](https://user-images.githubusercontent.com/9502098/89462619-ff214900-d76d-11ea-898c-873abfcfe5d0.png)

**Comment by wolfpld** [comment]
There are many things that may affect how "real time" data capture is. As mentioned earlier, symbol resolution will stall the connection for quite some time. This mainly happens at the beginning of profiling, when most of the symbols are discovered. The context switch data and call stack samples are collected when the OS decides it is time to dispatch data to the application.

The `???` zones should have proper names though.

**Comment by hugoam** [comment]
The `???` seem to get resolved progressively, but they quickly get stuck and don't seem to get resolved anymore and there are millions of things in the backlog
How can I do to ensure I get everything resolved, to allow the client to catch up on transmitting the data to the server ? Or a software toggle to tell tracy to stop profiling ?
Maybe I should try `TRACY_NO_EXIT` ?

**Comment by wolfpld** [comment]
> The ??? seem to get resolved progressively, but they quickly get stuck and don't seem to get resolved anymore and there are millions of things in the backlog

You need to wait for backlog to be processed. Eventually everything will be in place.

>  How can I do to ensure I get everything resolved, to allow the client to catch up on transmitting the data to the server ? Or a software toggle to tell tracy to stop profiling ?

When the application shuts down, the profiling session won't be terminated until all the needed data is transferred. You might be interrupting this process, for example by using the MSVC "stop" button, or by calling `exit()` from within the code. In such case there is no proper cleanup of objects in the program and the profiler cannot finish its work.

If you need to call `exit()`, instead put everything in the `main()` function into a `catch` block, then throw an exception.

>  Maybe I should try TRACY_NO_EXIT ?

No, this is for different purposes.

**Comment by hugoam** [comment]
> You need to wait for backlog to be processed. Eventually everything will be in place.

This is the problem. My application seems to fill the backlog quicker than it can be consumed, which is why I end up with a few millions entries there and it doesn't really go down

> When the application shuts down, the profiling session won't be terminated until all the needed data is transferred.

Ok, so I just need to exit the game cleanly then ? I'll try that.
