### ISSUE TITLE
Issues setting up Tracy to profile a shared library

### ISSUE THREAD

**Issue by arno-lunarg** [wolfpld/tracy#844]
Hello,

I am trying to setup Tracy (v 0.11) to profile a shared library (The Vulkan Validation Layer). I am working on Windows, but I also need things to work on Linux.
My setup almost works, I can get traces, but I have issues with Tracy lifetime, depending on Tracy setup variations I either crash or get stuck waiting for a Tracy thread (`s_symbolThread`).
I am trying to profile a single DLL, so I figured I should be able to use Tracy as a static library. Also tried to use Tracy as a DLL, and I had similar issues. Details:

Here is the branch with my changes to add Tracy: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8322
Relevant files are `CMakeLists.txt`, `layers/CMakeLists.txt`, `layers/profiling/profiling.cpp`
If needed, I can provide help on how to setup a build of the Vulkan Validation Layer to try to repro the issue. Some Vulkan applications to plug VVL into it will also be needed.

#### Manual lifetimes:

With `TRACY_DELAYED_INIT` and `TRACY_MANUAL_LIFETIME` enabled, I start Tracy in `DllMain`, and shut it down when we intercept `vkDestroyInstance`. Shutting down in `DllMain` caused a infinite wait for a Tracy worker thread when time to kill it, but reading the Windows doc, one should not do this kind of stuff in `DllMain`  so already lucky that I can start Tracy from here I guess. This issue is similar to automatic lifetimes, which I imagine makes sense since similar things happen in this case (?).
*Shutdown issue*: long wait in Tracy server (~ 1 minute) to empty query backlog, then crash in `TracyFree` (so after Tracy has been shutdown), probably due to static variables being freed (screenshot below). Trying to protect `TracyFree` with a `if (tracy::IsProfilerStarted())` lead to an infinite wait in a worker thread.

![tracy_static_manual_lifetime_wait_for_empty_query_backlog](https://github.com/user-attachments/assets/01905359-6b6c-40a2-97ca-901ae99d3ae7)

#### No manual lifetimes:

At shutdown, the Tracy server waits (around 30 seconds) for the query backlog to be emptied, then never ending wait in `WaitForSingleObject` for `s_symbolThread` when trying to destroy it:

![tracy_static_automatic_lifetime](https://github.com/user-attachments/assets/bee2502f-bd52-4e87-9640-708923d98eb2)

Tracy really is a nice tool, again I can get traces, and it already provided valuable insights into our layer, I just would love to be able to gracefully shutdown.

**Comment by wolfpld** [comment]
`IsProfilerStarted()` seems to be broken in its current state.

https://github.com/wolfpld/tracy/blob/684cee59abbcded4375f88152f3f7a706118cbe8/public/client/TracyProfiler.cpp#L1209-L1212

While `s_isProfilerStarted` is set correctly here, it can only protect against entering `MemFree`, etc. *after* it is set. If any code entered Tracy functions *before*, and especially if slow operations are being performed, such as getting a call stack, the profiler may well be destroyed before the code referencing the profiler finishes its work.

A proper solution should count how many outstanding operations are currently in process, with a spinlock right after setting `s_isProfilerStarted`, so that profiler destruction doesn't start too early.

FWIW, the API already provides macros (`TracySecureFree`, etc.) that do the check without a need for doing it manually by the user.

`IsProfilerStarted()` and `ProfilerAvailable()` maybe should be merged, as these provide very similar functionality, at least at the first glance.

**Comment by arno-lunarg** [comment]
Thank you for the quick reply, indeed switching to `TracySecureAlloc` and `TracySecureFree` fixed the crashes/dealock.
Per your valuable insights, I also removed calls to `IsProfilerStarted()`, given how I manage lifetimes they should not be needed anyway.

For posterity, if anyone happens to have similar issues, here is a link to my PR so that you can look at the code: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8322

And thank you Bartek for making this tool (and making it open source), it truly is amazing!
